### ISSUE TITLE
Throws error about missing babel dependency on require?

### ISSUE THREAD

**Issue by kevzettler** [aluc-io/request-animation-frame-polyfill#4]
```
var rafPolly = require('request-animation-frame-polyfill');

module.exports.request = rafPolly.requestAnimationFrame;
module.exports.cancel = rafPolly.cancelAnimationFrame;
```

```
Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault' from '/Users/kevzettler/code/fixed-game-loop/node_modules/request-animation-frame-polyfill/lib'
    at /Users/kevzettler/code/fixed-game-loop/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/kevzettler/code/fixed-game-loop/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/kevzettler/code/fixed-game-loop/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/kevzettler/code/fixed-game-loop/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/kevzettler/code/fixed-game-loop/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/kevzettler/code/fixed-game-loop/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:167:21)
```

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@kevzettler Thanks for reporting!
Sorry for the late resolution.
